//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winnie_Learning_Programme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int CertId { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string OrgName { get; set; }
        public string Url { get; set; }
        public string CertForm { get; set; }
    
        public virtual User User { get; set; }
    }
}
