//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winnie_Learning_Programme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int CourseId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string CourseName { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Category { get; set; }
    }
}
