//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winnie_Learning_Programme
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTP
    {
        public int Id { get; set; }
        public decimal OTPCode { get; set; }
        public string Email { get; set; }
        public string Ref { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
