//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Winnie_Learning_Programme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public int UserId { get; set; }
        public string Major { get; set; }
        public int CourseId { get; set; }
        public string SocialName { get; set; }
        public string SocialLink { get; set; }
    
        public virtual User User { get; set; }
        public virtual Course Course { get; set; }
    }
}
